- op: add
  path: /spec/template/spec/serviceAccountName
  value: notification-controller
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        containerName: manager
        resource: limits.memory
