apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: ghcr.io/fluxcd/source-watcher
    newName: ghcr.io/fluxcd/source-watcher
    newTag: v0.10.0
