# permissions for end users to edit artifactgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: source-watcher
    app.kubernetes.io/managed-by: kustomize
  name: artifactgenerator-editor-role
rules:
- apiGroups:
  - source.extensions.fluxcd.io
  resources:
  - artifactgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.extensions.fluxcd.io
  resources:
  - artifactgenerators/status
  verbs:
  - get
