name: sync-labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
jobs:
  sync-labels:
    permissions:
      issues: write
      contents: read
    uses: fluxcd/gha-workflows/.github/workflows/labels-sync.yaml@v0.0.1
